spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wdy?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=PRC
    username: root
    password: 123456

  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
  # 2、多环境的切换（yml）
  #  profiles:
  #    active: dev1

  # 3、动态切换多环境
#（1）编译器运行参数指定环境：步骤Run/Debug Configurations》》》program arguments处添加代码：--spring.profiles.active=dev
#（2）编译器vm参数指定环境：VM arguments处添加代码：-Dspring.profiles.active=dev
#（3）cmd命令行方式指定（需要将项目打包成jar包）：
#  java -jar wdy_springboot_demo-0.0.1-SNAPSHOT.jar --spring.profiles.active=test

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 666
#  servlet:
#    context-path: /hello
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #是否将eureka自身作为应用注册到eureka注册中心，
    # 由于我们目前创建的应用是一个服务注册中心，而不是普通的应用。默认情况下，这个应用会向注册中心（也是它自己）注册它自己，设置为false表示禁止这种默认行为
    fetch-registry: false #为true时，可以启动，但报异常：Cannot execute request on any known server
    # 表示不去检索其他的服务，因为服务注册中心本身的职责就是维护服务实例，它也不需要去检索其他服务
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'


---
server:
  port: 6661
spring:
  profiles: dev1

---
server:
  port: 6662
spring:
  profiles: test


student:
  # 引用application.properties配置的变量值
  name: ${student.name:无名}
  age: 20
  sex: true
  birthday: 2020/07/03
  #############################################################
  # 默认可以不写引号，但只有双引号才会将其中的转义符进行转义，如换行符。而单引号内数据会将换行符原样输出
  #
  # List和数组：用中括号，中括号可以省略
  # map和对象： 用大括号
  #############################################################
  # Map类型数据可以写成：行内写法
  # {province: "陕\n西",city: 西安,zone: 莲湖区}
  location:
    province: "陕\n西"
    city: 西安
    zone: 莲湖区
  # List和数组类型可以写成：
  # - 篮球
  # - 跑步
  hobbies: [篮球,跑步]
  skills: [Java编程,金融]
  # 对象类型数据可以写成：
  # nickName: 旺财
  # strain: 哈士奇
  pet: {nickName: 旺财, strain: 哈士奇}
  email: 115@1.com
  userName: 管理员

